name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux:
    name: Build for Linux
    uses: ./.github/workflows/os-linux.yml

  #macos:
  #  name: Build for macOS
  #  uses: ./.github/workflows/os-macos.yml

  #windows:
  #  name: Build for Windows
  #  uses: ./.github/workflows/os-windows.yml
