name: Linux Build

on:
  workflow_call:
    secrets:
      API_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install CMake 4.3.2
        run: |
          wget -q https://github.com/Kitware/CMake/releases/download/v4.3.2/cmake-4.3.2-linux-x86_64.sh
          sudo bash cmake-4.3.2-linux-x86_64.sh --prefix=/usr/local --skip-license
          rm cmake-4.3.2-linux-x86_64.sh
          cmake --version

      - name: Install GCC
        uses: egor-tensin/setup-gcc@v2
        with:
          version: "15"

      - name: Configure
        run: cmake --preset linux-debug

      - name: Build
        run: cmake --build --preset linux-debug
