name: Windows Build

on:
  workflow_call:
    secrets:
      API_TOKEN:
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install CMake 4.3.2
        run: |
          curl -sL https://github.com/Kitware/CMake/releases/download/v4.3.2/cmake-4.3.2-windows-x86_64.zip -o cmake.zip
          Expand-Archive -Path cmake.zip -DestinationPath C:\tools\cmake-4.3.2
          echo "CMAKE_BIN=C:\tools\cmake-4.3.2\bin" >> $env:GITHUB_ENV

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Configure
        run: cmake --preset windows-debug

      - name: Build
        run: cmake --build --preset windows-debug --config Debug
