name: Windows Build

on:
  workflow_call:
    secrets:
      API_TOKEN:
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install CMake 4.3.2
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "4.3.2"

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Configure
        run: cmake --preset windows-debug

      - name: Build
        run: cmake --build --preset windows-debug --config Debug
