name: Windows Build

on:
  workflow_call:
    secrets:
      API_TOKEN:
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install CMake 4.3.2
        run: |
          curl -sL https://github.com/Kitware/CMake/releases/download/v4.3.2/cmake-4.3.2-windows-x86_64.msi -o cmake.msi
          msiexec /i cmake.msi /quiet /norestart
          echo "C:\Program Files\CMake\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          cmake --version

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Configure
        run: cmake --preset windows-debug

      - name: Build
        run: cmake --build --preset windows-debug --config Debug
